"""skema awal pipelio

Revision ID: f328c87a1167
Revises: 
Create Date: 2026-07-28 15:46:55.586710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f328c87a1167'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clustering_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sales_name', sa.String(length=255), nullable=False),
    sa.Column('quarter', sa.String(length=4), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('lead', sa.Float(), nullable=False),
    sa.Column('prospecting', sa.Float(), nullable=False),
    sa.Column('negotiating', sa.Float(), nullable=False),
    sa.Column('won', sa.Float(), nullable=False),
    sa.Column('lost', sa.Float(), nullable=False),
    sa.Column('hold', sa.Float(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('loss_rate', sa.Float(), nullable=False),
    sa.Column('cluster', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('silhouette_score', sa.Float(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'quarter', 'sales_name', name='uq_result_period_sales')
    )
    op.create_index(op.f('ix_clustering_results_sales_name'), 'clustering_results', ['sales_name'], unique=False)
    op.create_index('ix_results_period', 'clustering_results', ['year', 'quarter'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('pic', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_company'), 'customers', ['company'], unique=False)
    op.create_index(op.f('ix_customers_industry'), 'customers', ['industry'], unique=False)
    op.create_table('pipelines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('project_name', sa.String(length=500), nullable=False),
    sa.Column('project_category', sa.String(length=120), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=False),
    sa.Column('estimated_closing', sa.String(length=20), nullable=True),
    sa.Column('pic', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('sales_name', sa.String(length=255), nullable=True),
    sa.Column('quarter', sa.String(length=4), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipelines_customer'), 'pipelines', ['customer'], unique=False)
    op.create_index(op.f('ix_pipelines_industry'), 'pipelines', ['industry'], unique=False)
    op.create_index('ix_pipelines_period', 'pipelines', ['year', 'quarter'], unique=False)
    op.create_index('ix_pipelines_period_sales', 'pipelines', ['year', 'quarter', 'sales_name'], unique=False)
    op.create_index(op.f('ix_pipelines_sales_name'), 'pipelines', ['sales_name'], unique=False)
    op.create_index(op.f('ix_pipelines_stage'), 'pipelines', ['stage'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_name'), 'sales', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sales_id', sa.String(length=36), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sales_id'], ['sales.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sales_name'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_pipelines_stage'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_sales_name'), table_name='pipelines')
    op.drop_index('ix_pipelines_period_sales', table_name='pipelines')
    op.drop_index('ix_pipelines_period', table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_industry'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_customer'), table_name='pipelines')
    op.drop_table('pipelines')
    op.drop_index(op.f('ix_customers_industry'), table_name='customers')
    op.drop_index(op.f('ix_customers_company'), table_name='customers')
    op.drop_table('customers')
    op.drop_index('ix_results_period', table_name='clustering_results')
    op.drop_index(op.f('ix_clustering_results_sales_name'), table_name='clustering_results')
    op.drop_table('clustering_results')
    # ### end Alembic commands ###
